/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  access_roles: () => import("@/views/access/roles/index.vue"),
  access_users: () => import("@/views/access/users/index.vue"),
  channels_detail: () => import("@/views/channels/detail/[id].vue"),
  channels_list: () => import("@/views/channels/list/index.vue"),
  finance_accounts: () => import("@/views/finance/accounts/index.vue"),
  finance_ledger: () => import("@/views/finance/ledger/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "notifications_dead-letters": () => import("@/views/notifications/dead-letters/index.vue"),
  notifications_detail: () => import("@/views/notifications/detail/[taskNo].vue"),
  notifications_tasks: () => import("@/views/notifications/tasks/index.vue"),
  orders_detail: () => import("@/views/orders/detail/[orderNo].vue"),
  orders_list: () => import("@/views/orders/list/index.vue"),
  products_list: () => import("@/views/products/list/index.vue"),
  risk_decisions: () => import("@/views/risk/decisions/index.vue"),
  risk_lists: () => import("@/views/risk/lists/index.vue"),
  risk_rules: () => import("@/views/risk/rules/index.vue"),
  suppliers_list: () => import("@/views/suppliers/list/index.vue"),
};
