/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'access',
    path: '/access',
    component: 'layout.base',
    meta: {
      title: '后台权限',
      icon: 'mdi:shield-account-outline',
      order: 2
    },
    children: [
      {
        name: 'access_roles',
        path: '/access/roles',
        component: 'view.access_roles',
        meta: {
          title: '角色管理',
          order: 2,
          roles: ['SUPER_ADMIN', 'R_SUPER']
        }
      },
      {
        name: 'access_users',
        path: '/access/users',
        component: 'view.access_users',
        meta: {
          title: '后台用户',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER']
        }
      }
    ]
  },
  {
    name: 'channels',
    path: '/channels',
    component: 'layout.base',
    meta: {
      title: '渠道管理',
      icon: 'mdi:lan-connect',
      order: 3
    },
    children: [
      {
        name: 'channels_detail',
        path: '/channels/detail/:id',
        component: 'view.channels_detail',
        meta: {
          title: '渠道详情',
          hideInMenu: true,
          activeMenu: 'channels_list',
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'FINANCE']
        }
      },
      {
        name: 'channels_list',
        path: '/channels/list',
        component: 'view.channels_list',
        meta: {
          title: '渠道列表',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS']
        }
      },
      {
        name: 'channels_recharge',
        path: '/channels/recharge',
        component: 'view.channels_recharge',
        meta: {
          title: '渠道充值',
          order: 2,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'FINANCE']
        }
      }
    ]
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: '财务中心',
      icon: 'mdi:wallet-outline',
      order: 7
    },
    children: [
      {
        name: 'finance_accounts',
        path: '/finance/accounts',
        component: 'view.finance_accounts',
        meta: {
          title: '账户信息',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'FINANCE']
        }
      },
      {
        name: 'finance_ledger',
        path: '/finance/ledger',
        component: 'view.finance_ledger',
        meta: {
          title: '账务流水',
          order: 2,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'FINANCE']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '工作台',
      icon: 'mdi:view-dashboard-outline',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: '登录',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'notifications',
    path: '/notifications',
    component: 'layout.base',
    meta: {
      title: '通知管理',
      icon: 'mdi:bell-outline',
      order: 8
    },
    children: [
      {
        name: 'notifications_dead-letters',
        path: '/notifications/dead-letters',
        component: 'view.notifications_dead-letters',
        meta: {
          title: '通知死信',
          order: 2,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'SUPPORT']
        }
      },
      {
        name: 'notifications_detail',
        path: '/notifications/detail/:taskNo',
        component: 'view.notifications_detail',
        meta: {
          title: '通知详情',
          hideInMenu: true,
          activeMenu: 'notifications_tasks',
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'SUPPORT']
        }
      },
      {
        name: 'notifications_tasks',
        path: '/notifications/tasks',
        component: 'view.notifications_tasks',
        meta: {
          title: '通知任务',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'SUPPORT']
        }
      }
    ]
  },
  {
    name: 'orders',
    path: '/orders',
    component: 'layout.base',
    meta: {
      title: '订单中心',
      icon: 'mdi:clipboard-list-outline',
      order: 6
    },
    children: [
      {
        name: 'orders_detail',
        path: '/orders/detail/:orderNo',
        component: 'view.orders_detail',
        meta: {
          title: '订单详情',
          hideInMenu: true,
          activeMenu: 'orders_list',
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'SUPPORT']
        }
      },
      {
        name: 'orders_list',
        path: '/orders/list',
        component: 'view.orders_list',
        meta: {
          title: '订单列表',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS', 'SUPPORT']
        }
      }
    ]
  },
  {
    name: 'products',
    path: '/products',
    component: 'layout.base',
    meta: {
      title: '商品中心',
      icon: 'mdi:cube-outline',
      order: 4
    },
    children: [
      {
        name: 'products_detail',
        path: '/products/detail/:id',
        component: 'view.products_detail',
        meta: {
          title: 'products_detail'
        }
      },
      {
        name: 'products_list',
        path: '/products/list',
        component: 'view.products_list',
        meta: {
          title: '平台商品',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS']
        }
      }
    ]
  },
  {
    name: 'risk',
    path: '/risk',
    component: 'layout.base',
    meta: {
      title: '风控管理',
      icon: 'mdi:shield-alert-outline',
      order: 5
    },
    children: [
      {
        name: 'risk_decisions',
        path: '/risk/decisions',
        component: 'view.risk_decisions',
        meta: {
          title: '风控决策',
          order: 3,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'RISK']
        }
      },
      {
        name: 'risk_lists',
        path: '/risk/lists',
        component: 'view.risk_lists',
        meta: {
          title: '黑白名单',
          order: 2,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'RISK']
        }
      },
      {
        name: 'risk_rules',
        path: '/risk/rules',
        component: 'view.risk_rules',
        meta: {
          title: '风控规则',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'RISK']
        }
      }
    ]
  },
  {
    name: 'suppliers',
    path: '/suppliers',
    component: 'layout.base',
    meta: {
      title: '供应商管理',
      icon: 'mdi:truck-delivery-outline',
      order: 4.5
    },
    children: [
      {
        name: 'suppliers_detail',
        path: '/suppliers/detail/:id',
        component: 'view.suppliers_detail',
        meta: {
          title: '供应商详情',
          hideInMenu: true,
          activeMenu: 'suppliers_list',
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS']
        }
      },
      {
        name: 'suppliers_list',
        path: '/suppliers/list',
        component: 'view.suppliers_list',
        meta: {
          title: '供应商列表',
          order: 1,
          roles: ['SUPER_ADMIN', 'R_SUPER', 'OPS']
        }
      }
    ]
  }
];
